#!/usr/bin/env python3
"""
Bundle all course content (markdown lessons, grammar, JSON quizzes, CSV decks)
into a single js/content.js file so the web app works without fetching files.

Run after editing any .md / .json / .csv in the course folders:
    python3 tools/build-content.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

INCLUDE_PATTERNS = [
    "lecciones/*.md",
    "gramatica/*.md",
    "quizzes/*.json",
    "quizzes/*.md",
    "flashcards/*.csv",
    "examen/*.md",
    "conversacion/*.md",
    "plan/*.md",
]

bundle = {}
for pattern in INCLUDE_PATTERNS:
    for path in sorted(ROOT.glob(pattern)):
        rel = path.relative_to(ROOT).as_posix()
        bundle[rel] = path.read_text(encoding="utf-8")

header = (
    "// AUTO-GENERATED by tools/build-content.py — do NOT edit by hand.\n"
    "// Re-run the script after editing any course markdown/JSON/CSV.\n"
    "// Bundles every course asset so the app works offline / standalone.\n\n"
)
js = header + "const LATVISKY_CONTENT = " + json.dumps(
    bundle, ensure_ascii=False, separators=(",", ":")
) + ";\n"

out_path = ROOT / "js" / "content.js"
out_path.write_text(js, encoding="utf-8")

total_bytes = sum(len(v) for v in bundle.values())
print(
    f"✅ Wrote {out_path.relative_to(ROOT)}\n"
    f"   - {len(bundle)} files bundled\n"
    f"   - {total_bytes:,} bytes of source content\n"
    f"   - {len(js):,} bytes total in content.js"
)
